// export const DROPDOWN_LANGS = ['الإنجليزية', 'عربى']
// export const BUTTONS = ['حفظ','حذف','واضح','إلغاء','تحديث']

// export const ApplicationSetting =['إعدادات التطبيق' , 'إعدادات التطبيق' , 'اسم العميل باللغة الإنجليزية' ,'الاسم المختصر للعميل باللغة الإنجليزية', 'اسم العميل العربي', 'الاسم المختصر باللغة العربية للعميل']
// export const ApplicationType = 'نوع التطبيق'
// export const Abbrevation = 'نوع التطبيق الاختصار'
// export const ApplicationTypeArabic = 'نوع التطبيق عربي'
// export const ApplicationTypeEnglish = 'نوع التطبيق الإنجليزية'
// export const ApplicationNoFormula = 'تطبيق لا الفورمولا'
// export const SubmissionGroup ='مجموعة التقديم'
// export const Publish = 'ينشر'
// export const  HasWorkFlow ='لديه تدفق العمل'
// export const AppWorkTypeTable = ['تحديد' , 'تطبيق لا اختصار' , 'نوع التطبيق الإنجليزية' ,'نوع التطبيق عربي' ,'تعديل']
// export const ApplicationStatus ='حالة التطبيق'
// export const StatusEnglishName = 'الحالة الاسم الإنجليزي'
// export const StatusArabicName = 'الحالة الاسم باللغة العربية'
// export const IsStartPoint = 'هي نقطة البداية'
// export const IsEndPoint = 'هو نقطة النهاية'
// export const ApproveStatus = 'الموافقة على الحالة'
// export const ApproveEnglishCaption  ='الموافقة على التسمية التوضيحية الإنجليزية'
// export const ApproveArabicCaption = 'اعتماد التسمية التوضيحية العربية'
// export const RejectStatus = 'رفض الحالة'
// export const RejectEnglishCaption = 'رفض التسمية التوضيحية الإنجليزية'
// export const RejectArabicCaption =  'رفض التسمية التوضيحية العربية'
// export const RequestMoreInfoStatus = 'طلب مزيد من المعلومات الحالة'
// export const RequestInfoEnglishCaption =' طلب معلومات باللغة الإنجليزية'
// export const RequestInfoArabicCaption = 'طلب معلومات التسمية التوضيحية العربية' 
// export const UserGroup = 'مجموعة المستخدمين'
// export const OrganizationUnit = 'وحدة التنظيم'
// export const SpecificUser = 'مستخدم معين'
// export const Company = 'Company'
// export const Active = 'Active'
// export const appStatusTable = ['Status Name English','Status Name Arabic' , 'Created Date' ,'تعديل' , 'Escalation(0)' ]
// export const ApplicationDesign = 'Application Field'
// export const Panelarabictitle = 'Panel arabic title'
// export const SavePanel = 'Save Panel'
// export const ApplicationOutputTemplate = 'Application Output Template'
// export const AddParameters = 'Add Parameters'
// export const DownloadEnglishTemplate  = 'Download English Template '
// export const AddArabicParameters = 'Add Arabic Parameters'
// export const DownloadArabicTemplate = 'Download Arabic Template'

// export const Caption = 'Caption'
// export const ArabicCaption = 'Arabic Caption'
// export const Type = 'Type'
// export const IsMandatory = 'Is Mandatory'
// export const IsUnique = 'Is Unique'
// export const IsIndexed= 'Is Indexed'
// export const IsHidden = 'Is Hidden'


// export const AddEscalation = 'Add Escalation'
// export const EsclalationName = 'Esclalation Name'
// export const NumberOfDays = 'عدد الايام'
// export const ActionToBePerformed = 'Action To Be Performed'
// export const SendNotification = 'Send Notification'
// export const ApproveApplication = 'Approve Application'
// export const RejectApplication ='Reject Application'
// export const RequestMoreInformationApplication = 'Request More Information Application'
// export const ChangeApplicationToNewStatus = 'Change Application To New Status'
// export const NotificationGroup = 'Notification Group'
// export const Save = 'Save'
// export const Delete = 'Delete'
// export const Clear = 'Clear'
// export const Escalationtabl= ['اختيار','Escalation Name','عدد الايام' ,'تعديل' ]
// export const DefineUser =['اختيار', 'User ID' , 'User FullName' , 'Group ID', 'User Email' ,'Job Description', 'تعديل'] 
// export const CreateNewUser ='Create New User'
// export const OrganizationStructure = 'Organization Structure'
// export const EnglishName ='English Name'
// export const ArabicName = 'Arabic Name'
// export const ShortName = 'Short Name'
// export const Address = 'Address'
// export const PhoneNo = 'Phone No'
// export const Fax = 'Fax'
// export const URL = 'URL'
// export const CompanyLevels = 'Company Levels'
// export const LevelName = 'Level Name'
// export const LevelArabicName ='Level Arabic Name'
// export const EntityInfo = 'Entity Info'
// export const EntityCode = 'Entity Code'
// export const OrganizationLevels = 'Organization Levels'
// export const Organization = 'Organization'
// export const FieldValue = 'Field Value'
// export const FieldText = 'Field Text'
// export const FieldTextArabic = 'Field Text Arabic'
// export const FieldOrder = 'Field Order'
// export const Select = 'اختيار'
// export const Action = 'الاجراء'
// export const AppTypeApplications = 'App Type Applications'
// export const ToDate = 'To Date'
// export const FromDate = 'From Date'
// export const Search = 'Search'
// export const AppTypeAppTable = ['اختيار' ,'رقم الطلب','نوع الطلب','حالة الطلب','تاريخ الطلب', 'الاجراء']
// export const NotificationType = 'Notification Type'
// export const NotificationTypeTable = ['Type Name English' ,'Type Name Arabic','Email Notification Template English','SMS Notification Template English','تعديل']
// export const Check ='Check'
// export const HasEmail = 'Has Email'
// export const SendImmidiately = 'Send Immidiately'
// export const SpecificTime = 'Specific Time'
// export const HasSMS ='Has SMS'
// export const SendAtSpecificTime = 'Send At Specific Time'
// export const Update = "Update"
// export const EamilTemplate = 'Eamil Template'
// // export const RequestMoreInfoStatus = 'Request More Info Status'
// export const EnglishEmailTemplate ="English Email Template"
// export const ArabicEmailTemplate = "Arabic Email Template"
// export const SMSTemplate = "SMS Template"
// export const ArabicSMSTemplate = "Arabic SMS Template"

// // today
// export const EmployeeDeputyAssignment = 'Employee Deputy Assignment'
// export const Employee ='Employee'
// export const Companies = 'Companies'
// export const SelectSpecificUser= "Select Specific User"
// export const UserInformation = 'User Information'
// export const UserId = 'User Id'
// export const Retrive = 'Retrive'
// export const UserName = 'User Name'
// export const StartDate = 'Start Date'
// export const ChooseAdate = 'Choose a date'
// export const  EndDate = 'تاريخ الانتهاء'
// export const EmployeeDeputyAssignmentTable = ['اختيار','Deputy Name','Employee Name','Start Date' ,'تاريخ الانتهاء']
// export const DocumentName ='اسم الوثيقة'
// export const EnterEnglishDocumentName = 'Enter English Document Name'
// export const ArabicDocumentName = 'Arabic Document Name'
// export const IsRequired = 'Is Required'
// export const DefineApplicationDocumentTable = ['اختيار','Document Name English','Document Name Arabic','تعديل']
// export const ApplicationPanels = 'Application Panels'
// export const CallType = 'Call Type'
// export const Get ='Get'
// export const Post = 'Post'
// export const Soap = 'Soap'
// export const Rest = 'Rest'
// export const Header = 'Header'
// export const Body = 'Body'
// export const CallOnLoad = 'Call On Load'
// export const WorkFlowApiTable = ['اختيار','Call Type','Api Path','الاجراء','Test','Parameter']
// export const AppTypelistTable =['رقم الطلب Abbreviation','نوع الطلب باللغة الانجليزية','نوع الطلب باللغة العربية','الاجراء','Add API'] 
// export const ApplicationNo = 'رقم الطلب'
// export const ApplicationDate ='تاريخ الطلب'
// export const ServiceType = 'Service Type'
// export const EmiratesId = 'Emirates Id'
// export const ApplicantName = 'Applicant Name'
// export const AppRequest = 'App Request'
// export const servicePaymentTable = ['نوع الطلب','رقم الطلب', 'تاريخ الطلب' , 'Amount (AED)' , 'Status', 'اختيار']
// export const finepayment = ['رقم الطلب','Fine','FineTerm','FineType','PaymentStatus','FineDate','FineAmount','اختيار']
// export const RequestforGeospatialMaps = 'Request for Geospatial Maps'
// export const MapType = 'Map Type'
// export const ReadyMap = 'Ready Map'
// export const CustomMap = 'Custom Map'
// export const ajmanSector1 = 'ajman Sector 1'
// export const ajmanSector2 = 'ajman Sector 2'
// export const ajmanSector3 = 'ajman Sector 3'
// export const ajmanSector4 = 'ajman Sector 4'
// export const ajmanDistrict1 = 'ajmanDistrict1'
// export const ajmanDistrict2 = 'ajmanDistrict2'
// export const ajmanDistrict3 = 'ajmanDistrict3'
// export const ajmanDistrict4 = 'ajmanDistrict4'
// export const MapLayer ='Map Layer'
// export const Layer1 = 'Layer1'
// export const Layer2 = 'Layer2'
// export const Layer3 = 'Layer3'
// export const A4 = 'A4'
// export const LegalSize = 'LegalSize'
// export const StandardSize = 'StandardSize'
// export const Add = 'Add+'
// export const GeospatialMaps = ['City','Map Size', 'اختيار', 'Upload']
// export const secondGeospatialMaps =['Sector','District', 'MapLayer','اختيار', 'Upload' ]
// export const ApplicationFiles ='Application Files'
// export const DocumentType = 'Document Type'
// export const AddFile = 'Add File'
// export const DocumentUploadTable = ['File Name','Document Type Name', 'Document Type Extension','الاجراء' ,'Download Here']
// export const ApplicationHistory = 'Application History'
// export const AuditHistoryLstTable = ['Decision Maker','Date Time','Current Status','الاجراء']
// export const DownloadForm = 'Download Form'
// export const Submit = 'Submit'
// export const Printreport = 'Print report'
// export const AssignedGroup = 'Assigned Group'
// export const AssignedUser = 'Assigned User'
// export const AllAppTable =['اختيار','رقم الطلب.', 'نوع الطلب', 'حالة الطلب', 'تاريخ الطلب', 'الاجراء']
// export const GoBack ='Go Back'
// export const ApplicationRequest = 'Application Request'
// export const VendorInformation = 'Vendor Information'
// export const Emirate = 'Emirate'
// export const LICENSEINFORMATION = 'LICENSE INFORMATION'
// export const LicenseNumber = 'LicenseNumber'
// export const REQUESTERINFORMATION ='REQUESTER INFORMATION'
// export const PrintReport = 'Print Report'
// export const Remarks = 'Remarks'
// export const Leaveacomment ='Leave a comment'
// export const AssignedAppTable = ['اختيار','رقم الطلب.', 'نوع الطلب', 'حالة الطلب', 'تاريخ الطلب','الاجراء']
// export const ApplicationHisoryTable  =['اختيار','رقم الطلب.','نوع الطلب','حالة الطلب','تاريخ الطلب','الاجراء']
// export const Applicant = 'Applicant'
// export const View = 'View'
// export const ApplicantionStatus ='Applicantion Status'
// export const ApplicationCountPerStatus = 'Application Count Per Status'

export const DROPDOWN_LANGS = ['English',  'Arabic']
export const BUTTONS = ['حفظ','حذف','مسح','الغاء','تحديث']
export const ApplicationSetting =['اعدادات النظام' , 'اعدادات النظام' , 'اسم العميل بالانجليزية' ,'اسم العميل المختصر بالانجليزية', 'اسم العميل بالعربية', 'اسم العميل المختصر بالعربية']
export const ApplicationType = 'نوع الطلب'
export const Abbrevation = 'رمز نوع الطلب'
export const ApplicationTypeArabic = 'نوع الطلب باللغة العربية'
export const ApplicationTypeEnglish = 'نوع الطلب باللغة الانجليزية'
export const ApplicationNoFormula = 'صيغة رقم الطلب'
export const SubmissionGroup ='مجموعة التقديم'
export const Publish = 'نشر'
export const HasWorkFlow ='HasWorkFlow'
export const AppWorkTypeTable = ['اختيار' , 'رمز رقم الطلب' , 'نوع الطلب باللغة الانجليزية' , 'نوع الطلب باللغة العربية' ,'تم نشره', 'الاجراء']


export const ApplicationStatus ='حالة الطلب'
export const StatusEnglishName = 'اسم الحالة باللغة الانجليزية'
export const StatusArabicName = 'اسم الحالة باللغة العربية'
export const IsStartPoint = 'نقطة بداية'
export const IsEndPoint = 'نقطة نهاية'
export const ApproveStatus = 'حالة الموافقة'
export const ApproveEnglishCaption  ='نص الموافقة باللغة الانجليزية'
export const ApproveArabicCaption = 'نص الموافقة باللغة العربية'
export const RejectStatus = 'حالة الرفض'
export const RejectEnglishCaption = 'نص الرفض باللغة الانجليزية'
export const RejectArabicCaption =  'نص الرفض باللغة العربية'
export const RequestMoreInfoStatus = 'حالة المزيد من المعلومات'
export const RequestInfoEnglishCaption ='نص المزيد من المعلومات باللغة الانجليزية'
export const RequestInfoArabicCaption = 'نص المزيد من المعلومات باللغة العربية' 
export const UserGroup = 'مجموعة المستخدم'
export const OrganizationUnit = 'وحدة المؤسسة'
export const SpecificUser = 'مستخدم محدد'
export const Company = 'الشركة'
export const Entity = 'وحدة العمل'
export const Active = 'نشط'
export const AllowEdit = 'السماح بالتعديل'
export const AllowUploadDocuments = 'السماح بتحميل الوثائق'
export const appStatusTable = ['اسم الحالة باللغة الانجليزية','اسم الحالة باللغة العربية' , 'تاريخ الانشاء' ,'تعديل' , 'التصعيد' ]
export const ApplicationDesign = 'حقل الطلب'
export const Panelarabictitle = 'عنوان اللوح باللغة العربية'
export const SavePanel = 'حفظ اللوح'
export const ApplicationOutputTemplate = 'نموذج مخرج الطلب'  
export const AddParameters = 'اضافة متغير'
export const DownloadEnglishTemplate  = 'تنزيل النموذج باللغة الانجليزية'
export const AddArabicParameters = 'اضافة متغير باللغة العربية'
export const DownloadArabicTemplate = 'تنزيل النموذج باللغة العربية'
export const Caption = 'النص'
export const ArabicCaption = 'النص باللغة العربية'
export const Type = 'النوع'
export const IsMandatory = 'اجباري'
export const IsUnique = 'مميز'
export const IsIndexed= 'مفهرس'
export const IsHidden = 'مخفي'


export const AddEscalation = 'اضافة تصعيد'
export const EsclalationName = 'اسم التصعيد'
export const NumberOfDays = 'عدد الايام'
export const ActionToBePerformed = 'الاجراء الذي سيتم اتخاذه'
export const SendNotification = 'ارسال اشعار'
export const ApproveApplication = 'الموفقة على الطلب'
export const RejectApplication ='رفض الطلب'
export const RequestMoreInformationApplication = 'طلب المزيد من المعلومات'
export const ChangeApplicationToNewStatus = 'تغير الطلب الى حالة جديدة'
export const NotificationGroup = 'مجموع الاشعار'
export const Save = 'حفظ'
export const Delete = 'حذف'
export const Clear = 'مسح'
export const Escalationtabl= ['اختيار','اسم التصعيد','عدد الايام' ,'تعديل' ]


export const DefineUser =['اختيار', 'اسم المستخدم' , 'اسم المستخدم الكامل' , 'رمز المجموعة', 'البريد الالكتروني للمستخدم' ,'الوصف الوظيفي', 'تعديل']
export const DefineNewGroup   ='اضافة مجموعة'
export const tableGroup = ['اسم المجموعة باللغة الانجليزية' ,'اسم المجموعة باللغة العربية','تعديل']

export const OrganizationStructure = 'هيكلية المؤسسة'
export const EnglishName ='الاسم بالانجليزية'
export const ArabicName = 'الاسم بالعربية'
export const ShortName = 'الاسم المختصر'
export const Address = 'العنوان'
export const PhoneNo = 'رقم الهاتف'
export const Fax = 'الفاكس'
export const URL = 'الموقع الالكتروني'
export const CompanyLevels = 'مستويات الشركة'
export const OrganizationLevels = 'مستويات المؤسسة'
export const Organization = 'المؤسسة'
export const LevelName = 'اسم المستوى'
export const LevelArabicName ='اسم المستوى باللغة العربية'
export const EntityInfo = 'معلومات وحدة العمل'
export const EntityCode = 'رمز وحدة العمل'
export const AllowTemplateDownload ='السماح بتنزيل النموذج'
export const  IntroductoryAR = 'نص المقدمة باللغة العربية'
export const  IntroductoryEn = 'نص المقدمة باللغة الانجليزية'

// today
export const FieldValue = 'قيمة الحقل '
export const FieldText = 'نص الحقل'
export const FieldTextArabic = 'نص الحقل باللغة العربية'
export const FieldOrder = 'ترتيب الحقل'
export const Select = 'اختيار'
export const Action = 'الاجراء'
export const AppTypeApplications = 'اضافة نوع الطلب'
export const ToDate = 'الى تاريخ'
export const FromDate = 'من تاريخ'
export const Search = 'بحث'

export const AppTypeAppTable = ['اختيار' ,'رقم الطلب','نوع الطلب','حالة الطلب','تاريخ الطلب', 'الاجراء']
export const NotificationType = 'نوع الاشعار'
export const NotificationTypeTable = ['اسم النوع باللغة الانجليزية' ,'اسم النوع باللغة العربية','نموذج البريد الالكتروني باللغة الانجليزية','نموذج الرسائل النصية القصيرة باللغة الانجليزية','تعديل']
export const Check ='المحددات'
export const HasEmail = 'يوجد بريد الكتروني'
export const SendImmidiately = 'ارسال فوري'
export const SpecificTime = 'وقت محدد'
export const HasSMS ='يوجد رسائل نصية قصيرة'
export const SendAtSpecificTime = 'ارسال في وقت محدد'
export const Update = "تحديث"
export const EamilTemplate = 'نموذج البريد الالكتروني '
// export const RequestMoreInfoStatus = 'Request More Info Status'
export const EnglishEmailTemplate ="نموذج البريد الالكتروني باللغة الانجليزية "
export const ArabicEmailTemplate = "نموذج البريد الالكتروني باللغة العربية"
export const SMSTemplate = "SMS Template"
export const ArabicSMSTemplate = "Arabic SMS Template"


export const EmployeeDeputyAssignment = 'تعيين نائب الموظف'
export const Employee ='الموظف'
export const Companies = 'الشركات'
export const SelectSpecificUser= "الرجاء اختيار مستخدم محدد"
export const UserInformation = 'معلومات المستخدم'
export const UserId = 'رمز المستخدم'
export const Retrive = 'استرجاع'
export const UserName = 'اسم المستخدم'
export const StartDate = 'تاريخ البداية'
export const ChooseAdate = 'الرجاء اختيار تاريخ'
export const  EndDate = 'تاريخ الانتهاء'
export const EmployeeDeputyAssignmentTable = ['اختيار','اسم النائب','اسم الموظف','تاريخ البداية' ,'تاريخ الانتهاء']
export const DocumentName ='اسم الوثيقة'
export const EnterEnglishDocumentName = 'الرجاء ادخال اسم الوثيقة باللغة الانجليزية'
export const ArabicDocumentName = 'اسم الوثيقة باللغة العربية'
export const IsRequired = 'مطلوب'
export const DefineApplicationDocumentTable = ['اختيار','اسم الوثيقة باللغة الانجليزية','اسم الوثيقة باللغة العربية','تعديل']
export const ApplicationPanels = 'الواح الطلبات'
export const CallType = 'نوع الربط'
export const Get ='Get'
export const Post = 'Post'
export const Soap = 'Soap'
export const Rest = 'Rest'
export const Header = 'Header'
export const Body = 'Body'
export const CallOnLoad = 'Call On Load'
export const WorkFlowApiTable = ['اختيار','نوع الربط','Api Path','الاجراء','فحص','المتغير']
export const AppTypelistTable =['رمز رقم الطلب','نوع الطلب باللغة الانجليزية','نوع الطلب باللغة العربية','الاجراء','اضافة API'] 
export const ApplicationNo = 'رقم الطلب'
export const ApplicationDate ='تاريخ الطلب'
export const ServiceType = 'Service Type'
export const EmiratesId = 'Emirates Id'
export const ApplicantName = 'Applicant Name'
export const AppRequest = 'تقديم طلب'
export const servicePaymentTable = ['نوع الطلب','رقم الطلب', 'تاريخ الطلب' , 'قيمة المخالفة' , 'حالة', 'اختيار']
export const finepayment = ['رقم الطلب','المخالفة','نص المخالفة','نوع المخالفة','حالة الدفع','تاريخ المخالفة','قيمة المخالفة','اختيار']
export const RequestforGeospatialMaps = 'طلب خرائط ومخططات مكانية'
export const MapType = 'نوع الخريطة'
export const ReadyMap = 'خرائط جاهزة'
export const CustomMap = 'خرائط حسب الطلب'
export const ajmanSector1 = 'قطاع عجمان 1'
export const ajmanSector2 = 'قطاع عجمان 2'
export const ajmanSector3 = 'قطاع عجمان 3'
export const ajmanSector4 = 'قطاع عجمان 4'
export const ajmanDistrict1 = 'حي عجمان 1'
export const ajmanDistrict2 = 'حي عجمان 2'
export const ajmanDistrict3 = 'حي عجمان 3'
export const ajmanDistrict4 = 'حي عجمان 4'
export const MapLayer ='طبقة الخريطة'
export const Layer1 = 'طبقة 1'
export const Layer2 = 'طبقة 2'
export const Layer3 = 'طبقة 2'
export const A4 = 'A4'
export const LegalSize = 'LegalSize'
export const StandardSize = 'StandardSize'
export const Add = 'اضافة'
export const GeospatialMaps = ['المدينة','حجم الخريطة', 'اختيار', 'تحميل']
export const secondGeospatialMaps =['القطاع','الحي', 'طبقة الخريطة','حجم ','اختيار', 'تحميل' ]
export const ApplicationFiles ='ملفات الطلب'
export const DocumentType = 'نوع الوثيقة'
export const AddFile = 'اضافة ملف'
export const DocumentUploadTable = ['اسم الملف','اسم نوع الوثيقة', 'صيغة نوع الوثيقة','الاجراء' ,'تنزيل هنا']
export const ApplicationHistory = 'تاريخ مراحل الطلب'
export const AuditHistoryLstTable = ['متخذ القرار','التاريخ و الوقت','الحالة الحالية','الاجراء']
export const DownloadForm = 'تنزيل الطلب'
export const Submit = 'تقديم'
export const Printreport = 'طباعة التقرير'
export const AssignedGroup = 'المجموعة المعنية'
export const AssignedUser = 'المستخدم المعني'
export const AllAppTable =['اختيار','رقم الطلب.', 'نوع الطلب', 'حالة الطلب', 'تاريخ الطلب', 'الاجراء']
export const GoBack ='الرجوع'
export const ApplicationRequest = 'تقديم طلب'
export const VendorInformation = 'معلومات البائع'
export const Emirate = 'الامارة'
export const LICENSEINFORMATION = 'معلومات الرخصة'
export const LicenseNumber = 'رقم الرخصة'
export const REQUESTERINFORMATION ='معلومات مقدم الطلب'
export const PrintReport = 'طباعة التقرير'
export const Remarks = 'الملاحظات'
export const Leaveacomment ='اترك تعليق'
export const AssignedAppTable = ['اختيار','رقم الطلب.', 'نوع الطلب', 'حالة الطلب', 'تاريخ الطلب','الاجراء']
export const ApplicationHisoryTable  =['اختيار','رقم الطلب.','نوع الطلب','حالة الطلب','تاريخ الطلب','الاجراء']
export const Applicant = 'مقدم الطلب'
export const View = 'عرض'
export const ApplicantionStatus ='حالة الطلب'
export const ApplicationCountPerStatus = 'عدد الطلبات حسب الحالة'
export const Total = 'مجموع';
export const Pending = 'قيد الانتظار';
export const Completed = 'منجز';
export const ApplicationStatusCount = 'عدد حالة التطبيق';
export const TodayTransactions = 'المعاملات اليوم'
export const Approved = 'وافق';
export const Rejected = 'مرفوض';
export const ApplicationStatistics = 'إحصائيات التطبيق';
export const QuickLinks = 'روابط سريعة';
export const Announcements = 'الإعلانات'
export const DashboardView = "عرض لوحة القيادة"
export const ServiceName = "اسم الخدمة"