export const DROPDOWN_LANGS = ['English',  'Arabic']
export const BUTTONS = ['Save','Delete','Clear','Cancel','Update']
export const ApplicationSetting =['Application Settings' , 'Application Settings' , 'Customer English Name' ,'Customer English Short Name', 'Customer Arabic Name', 'Customer Arabic Short Name']
export const ApplicationType = 'Application Type'
export const Abbrevation = 'Application Type Abbrevation'
export const ApplicationTypeArabic = 'Application Type Arabic'
export const ApplicationTypeEnglish = 'Application Type English'
export const ApplicationNoFormula = 'Application No Formula'
export const SubmissionGroup ='Submission Group'
export const Publish = 'Publish'
export const HasWorkFlow ='HasWorkFlow'
export const AppWorkTypeTable = ['Select' , 'Application No Abbreviation' , 'Application Type English' , 'Application Type Arabic' ,'Published', 'Action']


export const ApplicationStatus ='Application Status'
export const StatusEnglishName = 'Status English Name'
export const StatusArabicName = 'Status Arabic Name'
export const IsStartPoint = 'Is Start Point'
export const IsEndPoint = 'Is End Point'
export const ApproveStatus = 'Approve Status'
export const ApproveEnglishCaption  ='Approve English Caption'
export const ApproveArabicCaption = 'Approve Arabic Caption'
export const RejectStatus = 'Reject Status'
export const RejectEnglishCaption = 'Reject English Caption'
export const RejectArabicCaption =  'Reject Arabic Caption'
export const RequestMoreInfoStatus = 'Request More Info Status'
export const RequestInfoEnglishCaption =' Request Info English Caption'
export const RequestInfoArabicCaption = 'Request Info Arabic Caption' 
export const UserGroup = 'User Group'
export const OrganizationUnit = 'Organization Unit'
export const SpecificUser = 'Specific User'
export const Company = 'Company'
export const Entity = 'Entity'
export const Active = 'Active'
export const AllowEdit = 'Allow Edit'
export const AllowUploadDocuments = 'Allow Upload Documents'
export const appStatusTable = ['Status Name English','Status Name Arabic' , 'Created Date' ,'Edit' , 'Escalation(0)' ]
export const ApplicationDesign = 'Application Field'
export const Panelarabictitle = 'Panel arabic title'
export const SavePanel = 'Save Panel'
export const ApplicationOutputTemplate = 'Application Output Template'
export const AddParameters = 'Add Parameters'
export const DownloadEnglishTemplate  = 'Download English Template '
export const AddArabicParameters = 'Add Arabic Parameters'
export const DownloadArabicTemplate = 'Download Arabic Template'



export const Caption = 'Caption'
export const ArabicCaption = 'Arabic Caption'
export const Type = 'Type'
export const IsMandatory = 'Is Mandatory'
export const IsUnique = 'Is Unique'
export const IsIndexed= 'Is Indexed'
export const IsHidden = 'Is Hidden'


export const AddEscalation = 'Add Escalation'
export const EsclalationName = 'Esclalation Name'
export const NumberOfDays = 'Number Of Days'
export const ActionToBePerformed = 'Action To Be Performed'
export const SendNotification = 'Send Notification'
export const ApproveApplication = 'Approve Application'
export const RejectApplication ='Reject Application'
export const RequestMoreInformationApplication = 'Request More Information Application'
export const ChangeApplicationToNewStatus = 'Change Application To New Status'
export const NotificationGroup = 'Notification Group'
export const Save = 'Save'
export const Delete = 'Delete'
export const Clear = 'Clear'
export const Escalationtabl= ['Select','Escalation Name','Number of Days' ,'Edit' ]


export const DefineUser =['Select', 'User ID' , 'User FullName' , 'Group ID', 'User Email' ,'Job Description', 'Edit']
export const DefineNewGroup   ='Add Group'
export const tableGroup = ['Group English Name' ,'Group Arabic Name','Edit']

export const OrganizationStructure = 'Organization Structure'
export const EnglishName ='English Name'
export const ArabicName = 'Arabic Name'
export const ShortName = 'Short Name'
export const Address = 'Address'
export const PhoneNo = 'Phone No'
export const Fax = 'Fax'
export const URL = 'URL'
export const CompanyLevels = 'Company Levels'
export const OrganizationLevels = 'Organization Levels'
export const Organization = 'Organization'


export const LevelName = 'Level Name'
export const LevelArabicName ='Level Arabic Name'
export const EntityInfo = 'Entity Info'
export const EntityCode = 'Entity Code'
export const AllowTemplateDownload ='AllowTemplateDownload'

export const  IntroductoryAR = 'Introductory Text Arabic'
export const  IntroductoryEn = 'Introductory Text English'



// today
export const FieldValue = 'Field Value'
export const FieldText = 'Field Text'
export const FieldTextArabic = 'Field Text Arabic'
export const FieldOrder = 'Field Order'
export const Select = 'Select'
export const Action = 'Action'
export const AppTypeApplications = 'App Type Applications'
export const ToDate = 'To Date'
export const FromDate = 'From Date'
export const Search = 'Search'

export const AppTypeAppTable = ['Select' ,'Application No','Application Type','Application Status','Application Date', 'Action']
export const NotificationType = 'Notification Type'
export const NotificationTypeTable = ['Type Name English' ,'Type Name Arabic','Email Notification Template English','SMS Notification Template English','Edit']
export const Check ='Check'
export const HasEmail = 'Has Email'
export const SendImmidiately = 'Send Immidiately'
export const SpecificTime = 'Specific Time'
export const HasSMS ='Has SMS'
export const SendAtSpecificTime = 'Send At Specific Time'
export const Update = "Update"
export const EamilTemplate = 'Eamil Template'
// export const RequestMoreInfoStatus = 'Request More Info Status'
export const EnglishEmailTemplate ="English Email Template"
export const ArabicEmailTemplate = "Arabic Email Template"
export const SMSTemplate = "SMS Template"
export const ArabicSMSTemplate = "Arabic SMS Template"


export const EmployeeDeputyAssignment = 'Employee Deputy Assignment'
export const Employee ='Employee'
export const Companies = 'Companies'
export const SelectSpecificUser= "Select Specific User"
export const UserInformation = 'User Information'
export const UserId = 'User Id'
export const Retrive = 'Retrive'
export const UserName = 'User Name'
export const StartDate = 'Start Date'
export const ChooseAdate = 'Choose a date'
export const  EndDate = 'End Date'
export const EmployeeDeputyAssignmentTable = ['Select','Deputy Name','Employee Name','Start Date' ,'End Date']
export const DocumentName ='Document Name'
export const EnterEnglishDocumentName = 'Enter English Document Name'
export const ArabicDocumentName = 'Arabic Document Name'
export const IsRequired = 'Is Required'
export const DefineApplicationDocumentTable = ['Select','Document Name English','Document Name Arabic','Edit']
export const ApplicationPanels = 'Application Panels'
export const CallType = 'Call Type'
export const Get ='Get'
export const Post = 'Post'
export const Soap = 'Soap'
export const Rest = 'Rest'
export const Header = 'Header'
export const Body = 'Body'
export const CallOnLoad = 'Call On Load'
export const WorkFlowApiTable = ['Select','Call Type','Api Path','Action','Test','Parameter']
export const AppTypelistTable =['Application No Abbreviation','Application Type English','Application Type Arabic','Action','Add API'] 
export const ApplicationNo = 'Application No'
export const ApplicationDate ='Application Date'
export const ServiceType = 'Service Type'
export const EmiratesId = 'Emirates Id'
export const ApplicantName = 'Applicant Name'
export const AppRequest = 'App Request'
export const servicePaymentTable = ['Application Type','Application No', 'Application Date' , 'Amount (AED)' , 'Status', 'Select']
export const finepayment = ['ApplicationNumber','Fine','FineTerm','FineType','PaymentStatus','FineDate','FineAmount','Select']
export const RequestforGeospatialMaps = 'Request for Geospatial Maps'
export const MapType = 'Map Type'
export const ReadyMap = 'Ready Map'
export const CustomMap = 'Custom Map'
export const ajmanSector1 = 'ajman Sector 1'
export const ajmanSector2 = 'ajman Sector 2'
export const ajmanSector3 = 'ajman Sector 3'
export const ajmanSector4 = 'ajman Sector 4'
export const ajmanDistrict1 = 'ajmanDistrict1'
export const ajmanDistrict2 = 'ajmanDistrict2'
export const ajmanDistrict3 = 'ajmanDistrict3'
export const ajmanDistrict4 = 'ajmanDistrict4'
export const MapLayer ='Map Layer'
export const Layer1 = 'Layer1'
export const Layer2 = 'Layer2'
export const Layer3 = 'Layer3'
export const A4 = 'A4'
export const LegalSize = 'LegalSize'
export const StandardSize = 'StandardSize'
export const Add = 'Add'
export const GeospatialMaps = ['City','Map Size', 'Select', 'Upload']
export const secondGeospatialMaps =['Sector','District', 'MapLayer','Size','Select', 'Upload' ]
export const ApplicationFiles ='Application Files'
export const DocumentType = 'Document Type'
export const AddFile = 'Add File'
export const DocumentUploadTable = ['File Name','Document Type Name', 'Document Type Extension','Action' ,'Download Here']
export const ApplicationHistory = 'Application History'
export const AuditHistoryLstTable = ['Decision Maker','Date Time','Current Status','Action']
export const DownloadForm = 'Download Form'
export const Submit = 'Submit'
export const Printreport = 'Print report'
export const AssignedGroup = 'Assigned Group'
export const AssignedUser = 'Assigned User'
export const AllAppTable =['Select','Application No.', 'Application Type', 'Application Status', 'Application Date', 'Action']
export const GoBack ='Go Back'
export const ApplicationRequest = 'Application Request'
export const VendorInformation = 'Vendor Information'
export const Emirate = 'Emirate'
export const LICENSEINFORMATION = 'LICENSE INFORMATION'
export const LicenseNumber = 'LicenseNumber'
export const REQUESTERINFORMATION ='REQUESTER INFORMATION'
export const PrintReport = 'Print Report'
export const Remarks = 'Remarks'
export const Leaveacomment ='Leave a comment'
export const AssignedAppTable = ['Select','Application No.', 'Application Type', 'Application Status', 'Application Date','Action']
export const ApplicationHisoryTable  =['Select','Application No.','Application Type','Application Status','Application Date','Action']
export const Applicant = 'Applicant'
export const View = 'View'
export const ApplicantionStatus ='Applicantion Status'
export const ApplicationCountPerStatus = 'Application Count Per Status'
export const Total = 'Total';
export const Pending = 'Pending';
export const Completed = 'Completed';
export const ApplicationStatusCount = 'Application Status Count';
export const TodayTransactions = 'Today Transactions';
export const Approved = 'Approved';
export const Rejected = 'Rejected';
export const ApplicationStatistics = 'Application Statistics';
export const QuickLinks = 'Quick Links'
export const Announcements = 'Announcements'
export const DashboardView = "Dashboard View"
export const ServiceName = "Service Name"